apiVersion: v1
kind: Pod # type of resource example pod
metadata:
  name: pod-01 # name of the pod
spec:
 containers:
  - name: nginx # name of the container
    image: nginx:1.14.2 # image for the container
kind: Pod 
metadata:
  name: pod-01
spec: 
 containers:
  - name: nginx 
    image: nginx:1.14.2 
    ports:
      - containerPort: 80 
