apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx
      resources: ## providing resouces to allocate exact resources only
        requests:
          cpu: "100m" # 1/10 of cpu
          memory: "68Mi"
        limits:
          cpu: "120m"
          memory: "120Mi"
    - name: tomcat
      image: tomee
      resources:
        requests:
          cpu: "100m"
          memory: "120Mi"