apiVersion: v1
kind: Pod
metadata:
  name: secrete-pod
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
      - secretRef: # taking secretes from 11-secrets.yml file using name: secrete-01 secrete name
          name: secrete-01 # taking data as key and value pairs we can see in env