apiVersion: v1
kind: Service
metadata:
  name: demo-serclu-01
spec:
  selector:
    project: k1
    company: kvb
  ports:
  - protocol: TCP
    port: 80 #Service port
    targetPort: 80 #Container port