apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    company: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30037