apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs-demo
spec:
  replicas: 3
  selector:
    matchLabels:
        app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
    spec:
      containers:
        - name: nginx
          image: nginx

