apiVersion: v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matachLabels:
      labels:
        app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
    spec:
      containers:
        - name: nginx
          image: nginx

